### ISSUE TITLE
PHP-CS-Fixer Error: Error: Could not find 'php-cs-fixer'. The program may not be installed.

### ISSUE THREAD

**Issue by lemuthegreat** [Glavin001/atom-beautify#1324]
# Description

The results of beautification are not what I expect.

# Expected Results

The beautified code should have looked like:

```
<INSERT CODE HERE>
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/fe8188e9aecd79601afea771e2803ede

# Checklist

- [x] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] I have reloaded (or restarted) Atom to ensure it is not a caching issue
- [ ] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by lemuthegreat** [comment]
Since I came from other editors I'm new from Atom. And I can't seem to fix this error, Can anyone please help me? I'm a newbie when it comes to these type of things.

**Comment by lemuthegreat** [comment]
Since I came from other editors, I'm kind of new with Atom. Can anyone help me with this please?

**Comment by Glavin001** [comment]
Atom-Beautify uses PHP-CS-Fixer for beautifying PHP. There are a number of related issues: https://github.com/Glavin001/atom-beautify/search?q=Error%3A+Could+not+find+%27php-cs-fixer%27.+The+program+may+not+be+installed.&type=Issues&utf8=%E2%9C%93
I think a good one may be: https://github.com/Glavin001/atom-beautify/issues/394#issuecomment-111220120

See https://github.com/FriendsOfPHP/PHP-CS-Fixer for their installation instructions.

**Comment by Glavin001** [comment]
I really want to focus on improving the installation experience for users. I have created a new Issue, #1687, to target this problem. Please provide your feedback! Thanks in advance.

**Comment by phamthanhnghia** [comment]
**I fixed this.** You need uninstall **atom-beautify**

**Comment by cangelozzi** [comment]
Still having issue...uninstall atom-beautify...but no luck.  Not able to beautify php.

**Comment by szeck87** [comment]
If you've installed php-cs-fixer, make sure you set the path to it in atom beautify.  Open Atom Beautify's settings and expand "Executables".  Under that, expand "PHP-CS-Fixer" and set the path to it.
