### ISSUE TITLE
Installing “atom-beautify-0.29.16” failed.

### ISSUE THREAD

**Issue by Sykox** [Glavin001/atom-beautify#1472]
Installing “atom-beautify@0.29.16” failed.Hide output…

npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\Sykox\\AppData\\Local\\atom\\app-1.13.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Sykox\\AppData\\Local\\atom\\app-1.13.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Sykox\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Sykox\\.atom\\.apmrc" "install" "C:\\Users\\Sykox\\AppData\\Local\\Temp\\d-117016-7740-g5mo7w\\package.tgz" "--runtime=electron" "--target=1.3.13" "--arch=ia32" "--global-style" "--msvs_version=2015"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5

npm ERR! shasum check failed for C:\Users\Sykox\AppData\Local\Temp\npm-7696-ca27d1f9\registry.npmjs.org\gherkin\-\gherkin-2.12.2.tgz
npm ERR! Expected: 3c74547e466134a0ef83f614b1adfc489b70dc62
npm ERR! Actual:   22e5c2e74c038c79a4c2703808bde30bdbad3c58
npm ERR! From:     https://registry.npmjs.org/gherkin/-/gherkin-2.12.2.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Sykox\AppData\Local\Temp\apm-install-dir-117016-7740-1t4t3xv\npm-debug.log

**Comment by fernandopsilveira** [comment]
That happens to me too!

```
> atom-beautify@0.29.16 postinstall C:\Users\SISTEM~1\AppData\Local\Temp\apm-install-dir-117019-5952-4wx5y4\node_modules\atom-beautify
> npm run build-options

C:\Users\SISTEM~1\AppData\Local\Temp\apm-install-dir-117019-5952-4wx5y4
`-- (empty)


npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN deprecated minimatch@0.2.12: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated node-uuid@1.4.0: use uuid module instead
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at TLSSocket.addListener (events.js:239:17)
    at TLSSocket.Readable.on (_stream_readable.js:673:33)
    at Request.<anonymous> (C:\Users\Sistemas FS\AppData\Local\atom\app-1.13.0\resources\app\apm\node_modules\npm-registry-client\lib\request.js:153:7)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at ClientRequest.<anonymous> (C:\Users\Sistemas FS\AppData\Local\atom\app-1.13.0\resources\app\apm\node_modules\request\request.js:823:10)
    at emitOne (events.js:82:20)
    at ClientRequest.emit (events.js:169:7)
    at tickOnSocket (_http_client.js:502:7)
    at onSocketNT (_http_client.js:514:5)
'C:\Users\Sistemas' n�o � reconhecido como um comando interno
ou externo, um programa oper�vel ou um arquivo em lotes.
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\SISTEM~1\AppData\Local\Temp\apm-install-dir-117019-5952-4wx5y4\package.json'
npm WARN apm-install-dir-117019-5952-4wx5y4 No description
npm WARN apm-install-dir-117019-5952-4wx5y4 No repository field.
npm WARN apm-install-dir-117019-5952-4wx5y4 No README data
npm WARN apm-install-dir-117019-5952-4wx5y4 No license field.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Users\\Sistemas FS\\AppData\\Local\\atom\\app-1.13.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Sistemas FS\\AppData\\Local\\atom\\app-1.13.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Sistemas FS\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Sistemas FS\\.atom\\.apmrc" "install" "C:\\Users\\SISTEM~1\\AppData\\Local\\Temp\\d-117019-5952-1r762wl\\package.tgz" "--runtime=electron" "--target=1.3.13" "--arch=ia32" "--global-style"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! atom-beautify@0.29.16 postinstall: `npm run build-options`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the atom-beautify@0.29.16 postinstall script 'npm run build-options'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the atom-beautify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build-options
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs atom-beautify
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls atom-beautify
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\SISTEM~1\AppData\Local\Temp\apm-install-dir-117019-5952-4wx5y4\npm-debug.log
npm ERR! code 1
```

**Comment by adamderuwe** [comment]
Me as well.

**Comment by landreussi** [comment]
Try to run atom in Administrator mode, then install the plugin again. This worked to me

**Comment by adamderuwe** [comment]
I have a space in my Windows username.  I believe that is causing my problem.

`'C:\Users\Adam' is not recognized as an internal or external command, operable program or batch file.`

**Comment by Sonophis** [comment]
Same problem here with the space in the windows username.

`'C:\Users\John' is not recognized as an internal or external command, operable program or batch file.`

**Comment by BillyFrostick** [comment]
C:\Users\WILLIA~1\AppData\Local\Temp\apm-install-dir-117019-8828-amlgrn
`-- (empty)

It is not including my full username, and I have tried to run it in administrator mode.

**Comment by prettydiff** [comment]
The XXXXXX~1 directory convention is Microsoft's legacy support compromise to bridge support from its modern file systems to applications still supporting older file systems.  Back in the days of DOS (8 bit and 16 bit computing) directories would be slided off after 8 characters and filenames followed a 8.3 pattern where the file name could be 0-8 characters long with a file extension 1 to 3 characters long.  These naming conventions were single case and largely alpha-numeric, which means spaces were not supported.

The `~1` bit is there to prevent collisions.  Directories named `william goldman` and `william goldy` cannot both be converted to `WILLIAMG` as the name would have to be unique to its parent.  Instead they would be `WILLIA~1` and `WILLIA~2`.

I have observed, and I am probably wrong on this, that when running in 32bit mode modern Windows will still support legacy naming for backwards compatibility with Windows XP, but in 64bit mode Windows doesn't bother with these legacy conventions, at least not by default.

**Comment by nitmws** [comment]
The same problem with my two-parts Windows user name. Does anybody know a workaround?

**Comment by prettydiff** [comment]
This is an APM/NPM defect so unfortunately short of convincing other packages to publish with https://github.com/prettydiff/biddle there isn't a simple solution to this and it is out of our hands.

**Comment by grandeemme** [comment]
I have resolved by updating atom to 1.4.0 beta2

https://github.com/atom/apm/issues/666

**Comment by prettydiff** [comment]
It seems updating Atom and Atom-Beautify resolves these problems.  Please reopen this issue if there are on-going problems.

**Comment by Glavin001** [comment]
I've merged https://github.com/Glavin001/atom-beautify/pull/1598 which should resolve these issues.

Published to v0.29.21.

**Comment by M1chaelTran** [comment]
I'm still getting this error while trying to install the latest version `0.29.24`

```
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Users\\user\\AppData\\Local\\atom\\app-1.16.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\user\\AppData\\Local\\atom\\app-1.16.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\user\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\user\\.atom\\.apmrc" "install" "C:\\Users\\user\\AppData\\Local\\Temp\\d-117420-14624-1t5xxam.wu2z30izfr\\package.tgz" "--runtime=electron" "--target=1.3.13" "--arch=x64" "--global-style" "--msvs_version=2015"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.5

npm ERR! shasum check failed for C:\Users\user\AppData\Local\Temp\npm-7476-b0197b44\registry.npmjs.org\handlebars\-\handlebars-4.0.8.tgz
npm ERR! Expected: 22b875cd3f0e6cbea30314f144e82bc7a72ff420
npm ERR! Actual:   c2dfba1fcb8df8679ba77043c33d438b2ad855bf
npm ERR! From:     https://registry.npmjs.org/handlebars/-/handlebars-4.0.8.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\user\AppData\Local\Temp\apm-install-dir-117420-14624-143lfuv.dbrfojq0k9\npm-debug.log
```

**Comment by klubkard** [comment]
Getting this error on latest version `1.20.0 x64` with Atom-Beautify only.

```npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/zh/nbq0rwds3518pbt4bwlsfclh0000gn/T/apm-install-dir-117818-25329-cx0ne8.s8l3kmaemi/package.json'
npm WARN apm-install-dir-117818-25329-cx0ne8.s8l3kmaemi No description
npm WARN apm-install-dir-117818-25329-cx0ne8.s8l3kmaemi No repository field.
npm WARN apm-install-dir-117818-25329-cx0ne8.s8l3kmaemi No README data
npm WARN apm-install-dir-117818-25329-cx0ne8.s8l3kmaemi No license field.
npm ERR! Darwin 16.7.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/fk/.atom/.apm/.apmrc" "--userconfig" "/Users/fk/.atom/.apmrc" "install" "/private/var/folders/zh/nbq0rwds3518pbt4bwlsfclh0000gn/T/d-117818-25329-1m33yu5.vvtg74x6r/package.tgz" "--runtime=electron" "--target=1.6.9" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! path /private/var/folders/zh/nbq0rwds3518pbt4bwlsfclh0000gn/T/apm-install-dir-117818-25329-cx0ne8.s8l3kmaemi/node_modules/atom-beautify/node_modules/js-beautify/js/bin/css-beautify.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/private/var/folders/zh/nbq0rwds3518pbt4bwlsfclh0000gn/T/apm-install-dir-117818-25329-cx0ne8.s8l3kmaemi/node_modules/atom-beautify/node_modules/js-beautify/js/bin/css-beautify.js'
npm ERR! enoent ENOENT: no such file or directory, chmod '/private/var/folders/zh/nbq0rwds3518pbt4bwlsfclh0000gn/T/apm-install-dir-117818-25329-cx0ne8.s8l3kmaemi/node_modules/atom-beautify/node_modules/js-beautify/js/bin/css-beautify.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/zh/nbq0rwds3518pbt4bwlsfclh0000gn/T/apm-install-dir-117818-25329-cx0ne8.s8l3kmaemi/npm-debug.log
npm ERR! code 1```

**Comment by dhananjayaS** [comment]
Hi All,
I am getting this issue when installing atom beautify

Installing “atom-beautify@0.30.9” failed.Hide output…

npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! Linux 4.10.0-40-generic
npm ERR! argv "/opt/atom/resources/app/apm/bin/node" "/opt/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/dhananjaya/.atom/.apm/.apmrc" "--userconfig" "/home/dhananjaya/.atom/.apmrc" "install" "/tmp/d-1171030-12236-1ubutxx.nvpe97ldi/package.tgz" "--runtime=electron" "--target=1.6.15" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code EIO
npm ERR! errno -5
npm ERR! syscall read

npm ERR! EIO: i/o error, read
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-1171030-12236-1559unc.2lrd1v2t9/npm-debug.log

**Comment by Shivkrupa** [comment]
I am also getting the same error cloud anyone please help me out

**Comment by Shivkrupa** [comment]
I want help for this problem because again and again reinstalling ,but it is not working ...
