### ISSUE TITLE
Atom cannot install atom-beautify

### ISSUE THREAD

**Issue by homocomputeris** [Glavin001/atom-beautify#1855]
# Description

Atom cannot install the package. Other packages are installed with no issues.

# Input Before Beautification

This is what the code looked like before:

```
apm install atom-beautify
```

# Expected Output

Installation

# Actual Output

The beautified code actually looked like this:

```
(node:12370) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
Installing atom-beautify to /home/nik/.atom/packages ✗

npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-117818-12370-dtajds.fls3l/package.json'
npm WARN apm-install-dir-117818-12370-dtajds.fls3l No description
npm WARN apm-install-dir-117818-12370-dtajds.fls3l No repository field.
npm WARN apm-install-dir-117818-12370-dtajds.fls3l No README data
npm WARN apm-install-dir-117818-12370-dtajds.fls3l No license field.

npm ERR! path /tmp/apm-install-dir-117818-12370-dtajds.fls3l/node_modules/atom-beautify/node_modules/js-beautify/js/bin/css-beautify.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/tmp/apm-install-dir-117818-12370-dtajds.fls3l/node_modules/atom-beautify/node_modules/js-beautify/js/bin/css-beautify.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/nik/.atom/.apm/_logs/2017-09-18T08_58_09_389Z-debug.log
```

# Steps to Reproduce
Try to install via the UI or apm

# Debug

Here is a link to the `debug.md` Gist: <INSERT GIST HERE>

# Checklist

I have:
- [ ] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [ ] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by BiancoA** [comment]
same problem here:

`Installing atom-beautify to /Users/bianco/.atom/packages ✗
/private/var/folders/vh/40mq6lhd67v7ldyl5t35fd4r0000gn/T/apm-install-dir-117818-4020-1x02fj2.on7mgnl8fr
└── (empty)


npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/vh/40mq6lhd67v7ldyl5t35fd4r0000gn/T/apm-install-dir-117818-4020-1x02fj2.on7mgnl8fr/package.json'
npm WARN apm-install-dir-117818-4020-1x02fj2.on7mgnl8fr No description
npm WARN apm-install-dir-117818-4020-1x02fj2.on7mgnl8fr No repository field.
npm WARN apm-install-dir-117818-4020-1x02fj2.on7mgnl8fr No README data
npm WARN apm-install-dir-117818-4020-1x02fj2.on7mgnl8fr No license field.
npm ERR! Darwin 16.7.0
npm ERR! argv "/private/var/folders/vh/40mq6lhd67v7ldyl5t35fd4r0000gn/T/AppTranslocation/E391804E-AEFC-41E6-BBD1-FD6B1ECFEA66/d/Atom.app/Contents/Resources/app/apm/bin/node" "/private/var/folders/vh/40mq6lhd67v7ldyl5t35fd4r0000gn/T/AppTranslocation/E391804E-AEFC-41E6-BBD1-FD6B1ECFEA66/d/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/bianco/.atom/.apm/.apmrc" "--userconfig" "/Users/bianco/.atom/.apmrc" "install" "/private/var/folders/vh/40mq6lhd67v7ldyl5t35fd4r0000gn/T/d-117818-4020-1ev4at6.rmvtg74x6r/package.tgz" "--runtime=electron" "--target=1.6.9" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! path /private/var/folders/vh/40mq6lhd67v7ldyl5t35fd4r0000gn/T/apm-install-dir-117818-4020-1x02fj2.on7mgnl8fr/node_modules/atom-beautify/node_modules/js-beautify/js/bin/css-beautify.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/private/var/folders/vh/40mq6lhd67v7ldyl5t35fd4r0000gn/T/apm-install-dir-117818-4020-1x02fj2.on7mgnl8fr/node_modules/atom-beautify/node_modules/js-beautify/js/bin/css-beautify.js'
npm ERR! enoent ENOENT: no such file or directory, chmod '/private/var/folders/vh/40mq6lhd67v7ldyl5t35fd4r0000gn/T/apm-install-dir-117818-4020-1x02fj2.on7mgnl8fr/node_modules/atom-beautify/node_modules/js-beautify/js/bin/css-beautify.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/vh/40mq6lhd67v7ldyl5t35fd4r0000gn/T/apm-install-dir-117818-4020-1x02fj2.on7mgnl8fr/npm-debug.log
npm ERR! code 1
`

**Comment by michal037** [comment]
I have the same problem.

```
Installing “atom-beautify@0.30.5” failed.Hide output…
C:\Users\Michal\AppData\Local\Temp\apm-install-dir-117818-5168-1lrrx2o.1i9w4uz0k9
`-- (empty)


npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to 

graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Michal\AppData\Local\Temp\apm-install-dir-117818-5168-

1lrrx2o.1i9w4uz0k9\package.json'
npm WARN apm-install-dir-117818-5168-1lrrx2o.1i9w4uz0k9 No description
npm WARN apm-install-dir-117818-5168-1lrrx2o.1i9w4uz0k9 No repository field.
npm WARN apm-install-dir-117818-5168-1lrrx2o.1i9w4uz0k9 No README data
npm WARN apm-install-dir-117818-5168-1lrrx2o.1i9w4uz0k9 No license field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\Michal\\AppData\\Local\\atom\\app-1.20.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Michal\

\AppData\\Local\\atom\\app-1.20.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Michal\

\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Michal\\.atom\\.apmrc" "install" "C:\\Users\\Michal\\AppData\\Local\\Temp\\d-

117818-5168-1pzajjm.23kkv5cdi\\package.tgz" "--runtime=electron" "--target=1.6.9" "--arch=x64" "--global-style" "--

msvs_version=2015"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! path C:\Users\Michal\AppData\Local\Temp\apm-install-dir-117818-5168-1lrrx2o.1i9w4uz0k9\node_modules\atom-beautify

\node_modules\js-beautify\js\bin\css-beautify.js
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod 'C:\Users\Michal\AppData\Local\Temp\apm-install-dir-117818-5168-

1lrrx2o.1i9w4uz0k9\node_modules\atom-beautify\node_modules\js-beautify\js\bin\css-beautify.js'
npm ERR! enoent ENOENT: no such file or directory, chmod 'C:\Users\Michal\AppData\Local\Temp\apm-install-dir-117818-5168-

1lrrx2o.1i9w4uz0k9\node_modules\atom-beautify\node_modules\js-beautify\js\bin\css-beautify.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Michal\AppData\Local\Temp\apm-install-dir-117818-5168-1lrrx2o.1i9w4uz0k9\npm-debug.log
npm ERR! code 1
```

**Comment by szeck87** [comment]
@bitwiseman Looks like an issue with the latest js-beautify update?  I get the same error when I run `npm update` on my local repo.

**Comment by szeck87** [comment]
Waiting on https://github.com/beautify-web/js-beautify/pull/1251

**Comment by szeck87** [comment]
Please try installing it now.

**Comment by homocomputeris** [comment]
Thanks, it worked:

```
apm install atom-beautify

(node:2639) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
Installing atom-beautify to /home/nik/.atom/packages ✓
```

**Comment by szeck87** [comment]
Great, thanks.  Please ignore the deprecation warning for now, it will be fixed later.

**Comment by szeck87** [comment]
@bitwiseman Thanks for the quick turnaround.  @homocomputeris please close this issue if no more problems persist.

**Comment by arun2sasi** [comment]
Still am facing the problem 
Installing “atom-beautify@0.30.5” failed.Hide output…
C:\Users\SHANMU~1\AppData\Local\Temp\apm-install-dir-11799-6668-99xk1.z1pmohia4i
`-- (empty)


npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! tar.unpack untar error C:\Users\shanmugamarun\.atom\.apm\prettydiff\1.16.37\package.tgz
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\SHANMU~1\AppData\Local\Temp\apm-install-dir-11799-6668-99xk1.z1pmohia4i\package.json'
npm WARN apm-install-dir-11799-6668-99xk1.z1pmohia4i No description
npm WARN apm-install-dir-11799-6668-99xk1.z1pmohia4i No repository field.
npm WARN apm-install-dir-11799-6668-99xk1.z1pmohia4i No README data
npm WARN apm-install-dir-11799-6668-99xk1.z1pmohia4i No license field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\shanmugamarun\\AppData\\Local\\atom\\app-1.21.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\shanmugamarun\\AppData\\Local\\atom\\app-1.21.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\shanmugamarun\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\shanmugamarun\\.atom\\.apmrc" "install" "C:\\Users\\SHANMU~1\\AppData\\Local\\Temp\\d-11799-6668-fmim0n.teexijatt9\\package.tgz" "--runtime=electron" "--target=1.6.9" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! path C:\Users\SHANMU~1\AppData\Local\Temp\apm-install-dir-11799-6668-99xk1.z1pmohia4i\node_modules\.staging\prettydiff-a99742bb\api\prettydiff.wsf
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall open

npm ERR! Error: EPERM: operation not permitted, open 'C:\Users\SHANMU~1\AppData\Local\Temp\apm-install-dir-11799-6668-99xk1.z1pmohia4i\node_modules\.staging\prettydiff-a99742bb\api\prettydiff.wsf'
npm ERR!     at Error (native)
npm ERR!  { Error: EPERM: operation not permitted, open 'C:\Users\SHANMU~1\AppData\Local\Temp\apm-install-dir-11799-6668-99xk1.z1pmohia4i\node_modules\.staging\prettydiff-a99742bb\api\prettydiff.wsf'
npm ERR!     at Error (native)
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'open',
npm ERR!   path: 'C:\\Users\\SHANMU~1\\AppData\\Local\\Temp\\apm-install-dir-11799-6668-99xk1.z1pmohia4i\\node_modules\\.staging\\prettydiff-a99742bb\\api\\prettydiff.wsf',
npm ERR!   parent: 'atom-beautify' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\SHANMU~1\AppData\Local\Temp\apm-install-dir-11799-6668-99xk1.z1pmohia4i\npm-debug.log
npm ERR! code 1

**Comment by szeck87** [comment]
@arun2sasi Are you installing it through Atom or through the command prompt?  If the latter, are you running it as an administrator?

**Comment by ZeroDot1** [comment]
```bash
sudo apm install atom-beautify
(node:14505) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
Installing atom-beautify to /root/.atom/packages ✗

npm WARN deprecated graceful-fs@2.0.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated @types/commander@2.12.2: This is a stub types definition for commander (https://github.com/tj/commander.js). commander provides its own type definitions, so you don't need @types/commander installed!
npm WARN deprecated jscs-preset-wikimedia@1.0.1: Deprecated in favour of eslint-config-wikimedia. -- https://phabricator.wikimedia.org/T118941
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm ERR! code ERR_STREAM_WRITE_AFTER_END
npm ERR! write after end
npm ERR! code ERR_STREAM_WRITE_AFTER_END
npm ERR! write after end

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.atom/.apm/_logs/2018-03-30T18_03_45_088Z-debug.log

```

**Comment by mani261** [comment]
I have the same problem now, in new version. I tested both of command line and package installer.
Atom Version: 1.25.1 x64 - Windows 10

**Comment by kaliksharma** [comment]
i was having the same problem.. but i kept trying for 3-4 times and it finally got installed

**Comment by srabouin** [comment]
Had a similar problem, it was trying to unpack .atom/.apm/marko/4.13.3/package.tgz but 4.13.4 was there, I just renamed the 4.13.4 folder into 4.13.3 and installation went through... lazy fix :O

**Comment by kapeetano** [comment]
@srabouin  The problem was solved and worked for me,thanks,lazy fix :-)

**Comment by szeck87** [comment]
I just published v0.33.1.  For the time being, marko-prettyprint has been removed as there is an issue with the marko dependency when downloading.

**Comment by juzweb** [comment]
Hi, I tried to install in ATOM. and got this error:
Installing “atom-beautify@0.33.4” failed.Hide output…
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'C:\Users\Admin-pc\.atom\packages\atom-beautify\.github\no-response.yml

Can anyone look into it please? Thanks.

**Comment by josephpadgett82** [comment]
Can confirm that this issue has not resolved.  However, as others have said, I just did it four, then five times, and it finally installed correctly through Atom.

**Comment by ehimze007** [comment]
Installing “atom-beautify@0.33.4” failed.Hide output…

npm WARN deprecated graceful-fs@2.0.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm ERR! Unexpected end of JSON input while parsing near '...},"dist":{"shasum":"3'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\EHIMZE NATHANAEL\.atom\.apm\_logs\2019-10-16T16_33_17_327Z-debug.log


can't install the atom-beautify despite having attempted numerous times.

**Comment by neelesh93** [comment]
Installing “atom-beautify@0.33.4” failed.Hide output…

npm WARN deprecated graceful-fs@2.0.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated mkdirp@0.3.5: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated jscs-preset-wikimedia@1.0.1: No longer maintained. We recomment migrating to ESLint with eslint-config-wikimedia.
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\MRB15F~1.BLA\AppData\Local\Temp\apm-install-dir-120316-5884-10bqbkj.l23r\package.json'
npm WARN apm-install-dir-120316-5884-10bqbkj.l23r No description
npm WARN apm-install-dir-120316-5884-10bqbkj.l23r No repository field.
npm WARN apm-install-dir-120316-5884-10bqbkj.l23r No README data
npm WARN apm-install-dir-120316-5884-10bqbkj.l23r No license field.

npm ERR! path C:\Users\MRB15F~1.BLA\AppData\Local\Temp\apm-install-dir-120316-5884-10bqbkj.l23r\node_modules\atom-beautify\node_modules\htmlparser2
npm ERR! code EBUSY
npm ERR! errno -4082
npm ERR! syscall rename
npm ERR! EBUSY: resource busy or locked, rename 'C:\Users\MRB15F~1.BLA\AppData\Local\Temp\apm-install-dir-120316-5884-10bqbkj.l23r\node_modules\atom-beautify\node_modules\htmlparser2' -> 'C:\Users\MRB15F~1.BLA\AppData\Local\Temp\apm-install-dir-120316-5884-10bqbkj.l23r\node_modules\atom-beautify\node_modules\.htmlparser2.DELETE'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Mr. Black\.atom\.apm\_logs\2020-04-16T08_56_00_049Z-debug.log

**Comment by Ahmed-E-86** [comment]
I have the same issue:                                                               

```
npm WARN deprecated graceful-fs@2.0.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated mkdirp@0.3.5: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated @babel/polyfill@7.8.7: 🚨 This package has been deprecated in favor of separate inclusion of a polyfill and regenerator-runtime (when needed). See the @babel/polyfill docs (https://babeljs.io/docs/en/babel-polyfill) for more information.
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated jscs-preset-wikimedia@1.0.1: No longer maintained. We recomment migrating to ESLint with eslint-config-wikimedia.
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
Aborted (core dumped)
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-120426-35180-1ig118q.iobp/package.json'
npm WARN apm-install-dir-120426-35180-1ig118q.iobp No description
npm WARN apm-install-dir-120426-35180-1ig118q.iobp No repository field.
npm WARN apm-install-dir-120426-35180-1ig118q.iobp No README data
npm WARN apm-install-dir-120426-35180-1ig118q.iobp No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! core-js@2.6.11 postinstall: `node -e "try{require('./postinstall')}catch(e){}"`
npm ERR! Exit status 134
npm ERR! 
npm ERR! Failed at the core-js@2.6.11 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

**Comment by SagnikGuru** [comment]
can't install atom beautify


apm install atom-beautify
Installing atom-beautify to /home/sagnik/.atom/packages ✗

npm WARN deprecated graceful-fs@2.0.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated mkdirp@0.3.5: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated jscs-preset-wikimedia@1.0.1: No longer maintained. We recomment migrating to ESLint with eslint-config-wikimedia.
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: tough-cookie@~2.5.0 (node_modules/atom-beautify/node_modules/request/node_modules/tough-cookie):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Failed to parse json
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: No data, empty input at 1:1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ^
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: File: /home/sagnik/.atom/.apm/tough-cookie/2.5.0/package/package.json
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: mime-types@~2.1.19 (node_modules/atom-beautify/node_modules/request/node_modules/mime-types):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Failed to parse json
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: No data, empty input at 1:1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ^
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: File: /home/sagnik/.atom/.apm/mime-types/2.1.27/package/package.json
npm ERR! Linux 5.3.0-28-generic
npm ERR! argv "/opt/atom/resources/app/apm/bin/node" "/opt/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/sagnik/.atom/.apm/.apmrc" "--userconfig" "/home/sagnik/.atom/.apmrc" "install" "/tmp/d-120519-9331-1staved.owjdp1fw29/package.tgz" "--runtime=electron" "--target=1.7.11" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! file /home/sagnik/.atom/.apm/aws4/1.10.0/package/package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! No data, empty input at 1:1
npm ERR! 
npm ERR! ^
npm ERR! File: /home/sagnik/.atom/.apm/aws4/1.10.0/package/package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR! 
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-120519-9331-tqri4r.uw4xn4gqfr/npm-debug.log

**Comment by tatsuei** [comment]
Humble suggestion to everyone above who has not resolved this issue, could you try following the [official installation instructions](https://github.com/nodesource/distributions/blob/master/README.md) to manually install NodeJS v12 (or if needed, v14) and report back with results? I defaulted to the newest version, v14, then proceeded with installing the latest atom-beautify package **within** Atom itself, foregoing older versions suggested by answers I stumbled across on StackExchange.  

I encountered the same issue on Focal with the error code **npm ERR! code LIFECYCLE** , with detailed specs below:
OS: Ubuntu 20.04 LTS x86_64 
Host: Inspiron 5567 
Kernel: 5.4.0-39-generic
Shell: bash 5.0.16
CPU: Intel i5-7200U
GPU: AMD ATI Radeon R7 M440

**Comment by sameer0017** [comment]
npm WARN deprecated mkdirp@0.3.5: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated graceful-fs@2.0.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated jscs-preset-wikimedia@1.0.1: No longer maintained. We recomment migrating to ESLint with eslint-config-wikimedia.
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN lifecycle npm is using C:\Users\moham_iuiwsqj\AppData\Local\atom\app-1.50.0\resources\app\apm\bin\node.exe but there is no node binary in the current PATH. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
'node' is not recognized as an internal or external command,
operable program or batch file.
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\MOHAM_~1\AppData\Local\Temp\apm-install-dir-2020716-16216-1x6wn6i.gqmah\package.json'
npm WARN apm-install-dir-2020716-16216-1x6wn6i.gqmah No description
npm WARN apm-install-dir-2020716-16216-1x6wn6i.gqmah No repository field.
npm WARN apm-install-dir-2020716-16216-1x6wn6i.gqmah No README data
npm WARN apm-install-dir-2020716-16216-1x6wn6i.gqmah No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! core-js@2.6.11 postinstall: `node -e "try{require('./postinstall')}catch(e){}"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the core-js@2.6.11 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

can someone please look into it

**Comment by KHUSHIGUPTA335** [comment]
I AM ALSO NOT ABLE TO INSTALL ATOM - BEAUTIFY PACKAGE IN ATOM
SOMEONE KINDLY HELP


npm WARN deprecated graceful-fs@2.0.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated mkdirp@0.3.5: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated jscs-preset-wikimedia@1.0.1: No longer maintained. We recomment migrating to ESLint with eslint-config-wikimedia.
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm ERR! Unexpected end of JSON input while parsing near '...name":"front-matter",'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\khushi\.atom\.apm\_logs\2020-10-23T11_59_18_747Z-debug.log



THIS ERROR IT IS SHOWING..

**Comment by sintaawalisasng** [comment]
> 

can you tell me how to fix it?

**Comment by sintaawalisasng** [comment]
I'm almost frustrated
guys you only need to delete the .apm folder inside the .atom folder
Please try cz that's work for me:)))

**Comment by ahmedgadit** [comment]
Thanks @sintaawalisasng  it worked for linter, platformio-atom-ide-terminal and sync-settings i am almost getting this error for major of the extension all resolved now... Thank you so much

**Comment by herosam2021** [comment]
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated mkdirp@0.3.5: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated graceful-fs@2.0.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated @babel/polyfill@7.12.1: 🚨 This package has been deprecated in favor of separate inclusion of a polyfill and regenerator-runtime (when needed). See the @babel/polyfill docs (https://babeljs.io/docs/en/babel-polyfill) for more information.
npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm WARN deprecated uuid@2.0.3: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated jscs-preset-wikimedia@1.0.1: No longer maintained. We recomment migrating to ESLint with eslint-config-wikimedia.
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha512-zBhOgiSidx2ubKS+G2DP9M6lBpWbbuuI0MLIVWhiZeVXQYNz9vmcABE1OCFIH9+8xfcGbVYTG36skRcKrei1kA== integrity checksum failed when using sha512: wanted sha512-zBhOgiSidx2ubKS+G2DP9M6lBpWbbuuI0MLIVWhiZeVXQYNz9vmcABE1OCFIH9+8xfcGbVYTG36skRcKrei1kA== but got sha512-KICAUkaoiFzsB8AoDIz7pE5xHZSt20t36Eee4a6SNbAQjwEyC+uDlMX7qNAjclvUIBH/cdgEWiwBTbpCy1UMrQ==. (53273 bytes)
npm WARN registry Using stale data from https://registry.npmjs.org/ due to a request error during revalidation.
npm ERR! code EINTEGRITY
npm ERR! errno EINTEGRITY
npm ERR! Invalid response body while trying to fetch https://registry.npmjs.org/unified: Integrity verification failed for sha512-zBhOgiSidx2ubKS+G2DP9M6lBpWbbuuI0MLIVWhiZeVXQYNz9vmcABE1OCFIH9+8xfcGbVYTG36skRcKrei1kA== (C:\Users\sam\.atom\.apm\_cacache\content-v2\sha512\cc\18\4e8224a2771dae6ca4be1b60cff4cea506959b6eeb88d0c2c855686265e557418373f6f99c0011353821481fdfbcc5f7066d56131b7eac91170aade8b590)

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\sam\.atom\.apm\_logs\2021-08-15T08_58_25_064Z-debug.log

**Comment by herosam2021** [comment]
> 
> 
> I'm almost frustrated
> guys you only need to delete the .apm folder inside the .atom folder
> Please try cz that's work for me:)))

its not gone work
