### ISSUE TITLE
CSS beautify overzealous with spaces preceding pseudo elements

### ISSUE THREAD

**Issue by rediris** [Glavin001/atom-beautify#502]
`.example ::-webkit-input-placeholder` becomes `.example::-webkit-input-placeholder`

**Comment by Glavin001** [comment]
Please run `Atom Beautify: Help Debug Editor` from Atom command palette and put into a Markdown file (extension `.md`) in a Gist and paste the link back here. Thanks.

**Comment by rediris** [comment]
Thanks @Glavin001, here you go: https://gist.github.com/rediris/5477efe4cc6eda1e999e

**Comment by prettydiff** [comment]
I can't remember if Pretty Diff is used for regular CSS, but I can reproduce the error in Pretty Diff.

**Comment by prettydiff** [comment]
Fixed at http://prettydiff.com/ignore/testlocation/prettydiff.com.xhtml.  I will publish this fix soon.

**Comment by Glavin001** [comment]
> I can't remember if Pretty Diff is used for regular CSS, but I can reproduce the error in Pretty Diff.

Currently `JS Beautify` is used for regular CSS. See https://github.com/Glavin001/atom-beautify/blob/master/src/languages/css.coffee#L28

However, if Pretty Diff can pass all of the current tests that JS Beautify does for CSS, then I see no reason why we cannot do a silent migration for the default beautifier in Atom Beautify that users will not even notice, except for the superior support of Pretty Diff :smiley: .

> Fixed at http://prettydiff.com/ignore/testlocation/prettydiff.com.xhtml. I will publish this fix soon.

For users who want to use Pretty Diff as your beautifier, you can go into into the Atom Beautify package settings and find `Language Config - <language> - Default Beautifier` option and change it to `Pretty Diff`. For instance, `Language Config - CSS - Default Beautifier` is currently `JS Beautify` and you can change that to `Pretty Diff` and have this fixed!
Be sure to uninstall and reinstall Atom Beautify such that you get the latest update of Pretty Diff.

**Comment by Bubbi** [comment]
@Glavin001, I know this have been in the air for a while and this issue is still "open", but it doesn't seem like it is fixed in atom-beautify, even though prettydiff mentions that a fix was made.

For me, neither using **JS Beautify**, **CSS Comb** or **Pretty Diff** as **Default beautifier** works as expected.
It still removes a space before : (colon), which makes that CSS rule have a totally different behaviour.

If there is a reason for not doing anything to fix this or implement the mentioned fix, please update this issue ticket or comment.

**Comment by Glavin001** [comment]
@prettydiff is there a required option to make this fix in Pretty Diff work?

@Bubbi : Have you tried uninstalling and reinstalling Atom-Beautify? Often the issue is that your local copy of Pretty Diff is not the latest, although this issue is fairly old so that should not be the case. Maybe there is an option to get it to work.

To help @prettydiff and I debug this with you, please provide a link to the required `debug.md` Gist which includes debugging information that answers our most commonly asked questions: https://github.com/Glavin001/atom-beautify/blob/master/ISSUE_TEMPLATE.md#how-to-create-debugmd-gist
Thank you.

**Comment by prettydiff** [comment]
@Glavin001 This resolution does not require an option.  It was purely a defect that has since been resolved.

@Bubbi Could you please provide a code sample to ensure you are not talking a new defect that I am not aware of?

**Comment by prettydiff** [comment]
Closing as this issue is old and likely resolved.  If I am closing this issue prematurely please reopen it.
