### ISSUE TITLE
Method Chaining issue with prettydiff (jsx)

### ISSUE THREAD

**Issue by hayatae** [Glavin001/atom-beautify#591]
I'm not sure if behavior recently changed in prettydiff or atom-beautify or both, but when I beautify React (jsx) files, all of my chained methods are now broken up into individual lines instead of remaining on a single line. This never used to be a problem.

According to the atom-beautify setting for "Break chained methods" in JavaScript, this setting is only supported by JS Beautify. I don't see why this can't be supported by Pretty Diff as well since Pretty Diff has a setting for "methodchain" (http://prettydiff.com/documentation.xhtml). Granted its boolean value would be the opposite. As atom-beautify currently is, there is no way to adjust the method chaining setting that Pretty Diff uses, which means it always defaults to breaking chained methods.

For a workaround, I tried creating a .prettydiffrc file in my project root with the following settings:
{
  "methodchain": true
}

Unfortunately that didn't do the trick. I'm not sure if the file was ignored or if atom-beautify is overriding the settings.

Not sure if this is an issue for @prettydiff or atom-beautify or both.

Are there any workarounds or solutions for this?

**Comment by prettydiff** [comment]
This is due to a recent Pretty Diff change.  It is a very new method to Pretty Diff as I published it a little more than 2 weeks ago: https://github.com/prettydiff/prettydiff/issues/161

Look at this issue to track the status of Atom-Beautify support for new Pretty Diff options: https://github.com/Glavin001/atom-beautify/issues/524

> Granted its boolean value would be the opposite.

Before I published this feature/option to break method chains I did not support this in any way.  Once I added support I made the current behavior of breaking method chains the default behavior.  I provided the option only as a means to override this new default behavior.  Since the option is merely an override that returns method lists into a chain on a single line I named the option `methodchain` and its default value is `false` which corresponds to the default behavior of breaking chains onto individual lines.

I honestly didn't look to see if js-beautify had such an option, what its default behavior is, or how its naming convention/values work.

> I tried creating a .prettydiffrc file in my project root

The Atom-Beautify project does not use the `.prettydiffrc` file.  This project has its own internal option system that it has to use to bridge support from various formatting applications into a single API.  That and also the `.prettydiffrc` file is also very new at right about a month old.

What you can do for a work around is add this comment to your code:

    /*prettydiff.com methodchain:true*/

The order of precedence for options in Pretty Diff is the following from greatest to least:

1. The styleguide option (this only applies to the jspretty library)
2. The prettydiff comment
3. The `.prettydiffrc` file
4. User supplied options
5. Default option values

I will be updating the documentation to reflect this.

**Comment by prettydiff** [comment]
Did the comment resolve the problem?

**Comment by hayatae** [comment]
The comment only partially solves the problem. It enables method chaining for regular js code within the jsx file, but chained functions inside react tags are still broken into separate lines. For example:
[code]
        <div>
          {this.state.history.map(function (entry, i) {
            return (
              <button className="right-spacing" key={i} onClick={this.onHistoryClick.bind(this, entry)}>
                {entry.friendlyName}
              </button>
            );
          }, this)}
        </div>
[/code]
becomes:
[code]
        <div>
          {this
            .state
            .history
            .map(function (entry, i) {
              return (
                <button className="right-spacing" key={i} onClick={this
                  .onHistoryClick
                  .bind(this, entry)}>
                  {entry.friendlyName}
                </button>
              );
            }, this)}
        </div>
[/code]

And that's even with the comment present in the file. Obviously this is not at all desirable and makes the code very hard to read. Referencing this.state.<var> or this.props.<var> is very common in react and having all of that borken into separate lines is troublesome.

**Comment by prettydiff** [comment]
Thank you for bringing this to my attention.  The option should address this concern universally, which it isn't.  This is a defect I will fix tonight.

**Comment by prettydiff** [comment]
This appears to be fixed in the latest version of Pretty Diff and Pretty Diff 2.x is now in Atom Beautify.
