### ISSUE TITLE
jsx file - add extra space after function name

### ISSUE THREAD

**Issue by snowcxt** [Glavin001/atom-beautify#656]
define a function in jsx

``` javascript
submit(data) {
    //...
}
```

after formatting

``` javascript
submit (data) {
    //...
}
```

**Comment by Glavin001** [comment]
Pretty sure this is what you are looking for: https://github.com/Glavin001/atom-beautify/blob/master/docs/options.md#javascript---space-after-anon-function

**Comment by Glavin001** [comment]
I would recommend taking a look at...

Atom Beautify documentation: https://github.com/Glavin001/atom-beautify/blob/master/docs/options.md
Pretty Diff documentation: http://prettydiff.com/documentation.xhtml#options_definitions

/cc @prettydiff

**Comment by snowcxt** [comment]
But it formats js correctly meaning there is no extra space after the function name

**Comment by prettydiff** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Method_definitions

It seems with ES6 there is a convenience means for declaring methods directly by eliminating `:` and `function` keyword if in an object literal.  I will add this into the code.

    var obj = {
        foo() {},
        bar() {}
    };

If this issue is related to something other than this specific case I will need additional context.

**Comment by snowcxt** [comment]
Here is an example:

after formatting (ctrl + alt + b) the code becomes (an extra space after `render` function and the preview version of atom-beautify didn't add this extra space):

```javascript
import React, {
  Component
} from 'react';

export default class Format extends Component {
  render () {
    return <div>format issue</div>
  }
}

```

**Comment by prettydiff** [comment]
Please try it out at http://prettydiff.com/?m=beautify

**Comment by snowcxt** [comment]
seems that prettydiff can't recognize the syntax

**Comment by prettydiff** [comment]
Would you mind trying again?  I updated the language auto-detection to search for the pattern `/(\{|\s|;)render\s*\(\)\s*\{/` as JavaScript.

**Comment by snowcxt** [comment]
Now it works perfectly.

**Comment by snowcxt** [comment]
So will you fix this issue?

**Comment by prettydiff** [comment]
I will release an update soon and notify you when the new version is published.

**Comment by jgog** [comment]
Hey @prettydiff any update?

**Comment by prettydiff** [comment]
Sorry, this was resolved in one of the two prior releases.

**Comment by jgog** [comment]
issue still remains, try formatting this file, the indentation gets messed up:

```jsx
import React from 'react';

import styles from 'app/app.css';

const Label = React.createClass({
  displayName: 'Label',

  propTypes: {
    text: React.PropTypes.string,
    status: React.PropTypes.string
  },

  render() {
    let className = '';

    /* indent: false */
    switch (this.props.status) {
      case 'red':
        className = styles.labelRed;
        break;
      case 'blue':
        className = styles.labelBlue;
        break;
      case 'green':
        className = styles.labelGreen;
        break;
      case 'yellow':
        className = styles.labelYellow;
        break;
      case 'purple':
        className = styles.labelPurple;
        break;
      case 'gray':
        className = styles.labelGray;
        break;
      default:
        className = styles.label;
    }

    return (
      <span {...this.props} title={this.props.text} className={className}>{this.props.text}</span>
    );
  }

});

module.exports = Label;
```

becomes:
```jsx
...
switch (this.props.status) {
        case 'red ':
        className = styles.labelRed;
        break;
      case 'blue':
        className = styles.labelBlue;
        break;
      case 'green':
        className = styles.labelGreen;
        break;
      case 'yellow':
        className = styles.labelYellow;
        break;
      case 'purple':
        className = styles.labelPurple;
        break;
      case 'gray':
        className = styles.labelGray;
        break;
      default:
        className = styles.label;
    }
...
```

**Comment by prettydiff** [comment]
I cannot reproduce the problem at http://prettydiff.com/?m=beautify

Perhaps you need to update Pretty Diff locally.  You can uninstall and reinstall atom-beautify or run `npm install prettydiff` from the atom-beautify node_modules directory to update prettydiff directly.

**Comment by jgog** [comment]
same here :( and this doesn't work at all:

```jsx
import React from 'react';

import ...

export default class Trips extends React.Component {

  constructor() {
    super();
  }

  render() {
    return (
      <div id="trips" className={styles.container}>
          <TripsList {...this.props} />
      </div>
    );
  }
}
```

**Comment by prettydiff** [comment]
@jgog The problem with that code is the `...`.  That is supposed to be a spread operator: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_operator

The problem is that that line should be terminated with a semicolon, but Pretty Diff does not add a semicolon there for two reasons:

1. That does not look like a valid use for a spread operator
2. Statements do not typically terminate with operators:

    var a = "broken string" +
        "more string";  //prior line terminates with an operator... therefore no semicolon
        //this also means its really one continuous statement on two lines, which is just a vanity thing

If I am wrong and JSX has some silly convention with `...` that I am not aware of please let me know and I will fix it.

**Comment by jgog** [comment]
@prettydiff the `import ...` is for all the other import, I removed it after pasting it here, the spear operator is used only at `<TripsList {...this.props} />`

**Comment by prettydiff** [comment]
@jgog The latest code sample appears to work correctly at prettydiff.com with two minor changes:

* I had to remove the `import ...` line as this just represents etcetera instead of a literal operator
* I had to add `var a = 1;` to the first line of code so that the language auto-detection properly detected this as JavaScript.

In the next release this code sample will be detected to the proper language without having to add that `var a = 1;`.

**Comment by jgog** [comment]
The first point is obvious. Works with second point :+1:

**Comment by jgog** [comment]
@prettydiff Also, I was using Atom Beta 1.4.0-beta0 for the beautification in which it was breaking, I just tried it on a stable version and it worked fine.

**Comment by prettydiff** [comment]
Closing as this issue is likely resolved.  If I am in error please reopen the issue.
