### ISSUE TITLE
Pretty diff ignores html unformatted tags setting

### ISSUE THREAD

**Issue by rickysullivan** [Glavin001/atom-beautify#778]
Switching my html formatter to Pretty Diff means that my html unformatted tags setting is being ignored:

How can I get Pretty Diff to stop formatting tags that I want to remain inline?

```
  <em>
    Terms and Conditions
  </em>
```

**Comment by prettydiff** [comment]
Would you mind providing a slightly larger sample of code?  This sounds like a contextual problem and I will be able to provide better assistance if I can ensure I am meeting your request.

**Comment by rickysullivan** [comment]
```
<table border="0" cellpadding="0" cellspacing="0" width="500">
  <tr>
    <td align="center" style="font-family: Arial, sans-serif; font-size:10px; line-height:14px; text-align:left; color:#ccc;" valign="top">
      <span style="font-size:14px">
        <strong>
          <em>Terms and Conditions</em>
        </strong>
      </span><br>
      <br>
      If you would like to stop receiving SuperCoach
      <sup style="font-size: 10px; line-height: 0; vertical-align: 3px">&reg;</sup>
      game related emails please
      <a href="#" style="font-family: Arial, sans-serif; font-size:10px; line-height:12px; text-align:left; color:#7c7c7c; text-decoration:underline; font-weight: bold" target="_blank">Click Here</a>.
    </td>
  </tr>
</table>
```
I want ```span, a, strong, em, sup``` to be inline
```
<table border="0" cellpadding="0" cellspacing="0" width="500">
    <tr>
        <td align="center" style="font-family: Arial, sans-serif; font-size:10px; line-height:14px; text-align:left; color:#ccc;" valign="top">
            <span style="font-size:14px"><strong><em>Terms and Conditions</em></strong></span><br>
            <br>
            If you would like to stop receiving SuperCoach<sup style="font-size: 10px; line-height: 0; vertical-align: 3px">&reg;</sup> game related emails please <a href="#" style="font-family: Arial, sans-serif; font-size:10px; line-height:12px; text-align:left; color:#7c7c7c; text-decoration:underline; font-weight: bold" target="_blank">Click Here</a>.
        </td>
    </tr>
</table>
```

**Comment by rickysullivan** [comment]
Some more tests:

```
<span style="font-size:14px"><strong><em>Terms and Conditions</em></strong></span>

<span class="preheader">Preheader text goes here</span>

<strong>Terms and Conditions</strong>

<em> Terms and Conditions </em>

<strong><em>Terms and Conditions</em></strong>

<em><strong>Terms and Conditions</strong></em>
```

becomes:

```
<span style="font-size:14px">
    <strong>
        <em>Terms and Conditions</em>
    </strong>
</span>

<span class="preheader">Preheader text goes here</span>

<strong>Terms and Conditions</strong>

<em>
    Terms and Conditions
</em>

<strong>
    <em>Terms and Conditions</em>
</strong>

<em>
    <strong>Terms and Conditions</strong>
</em>
```

**Comment by rickysullivan** [comment]
Technically I should be applying style tags to format my text:
```
<span style="font-size:14px; font-weight: bold; font-style: italic;">Terms and Conditions</span>
```

Still, there are tags I'd rather keep inline and I can't find how to specify this setting.

**Comment by prettydiff** [comment]
I used to operate in this way years ago, but have since chosen a different direction.  I have found that indenting tags where possible (where such indentation does not alter the parsed output) really helps reading speed and understandability in the code.  I know this must seem contrary at first because when everything is indented it becomes harder to identify structure (block elements) from description (inline elements).

I partly came to this conclusion also because you cannot accurately and quickly discern the communicated intent of markup code by merely reading the code.  Markup code comes with a lot of helpers like CSS, ARIA, and even gets completely reordered due to JavaScript.  I had found that attempting to reason about the human consumable state of content by examining the code ultimately led to false positive assumptions about how the code actually works in front of the user which in turn results in lost productivity.

Beautification aside, as a matter of personal preference I never wrap an inline HTML element in another HTML inline element.  For instance:

    <strong>
        <em>Terms and Conditions</em>
    </strong>

Is that text supposed to be emphasized or emboldened?  This would be confusing to a text reader.  I suspect the goal is to present the text as bold and italicized both of which can be applied with CSS without changing the meaning of the text.  To achieve accessibility conformance the description upon a given instance of text should match the intended human consumable function (emotion and direction) of that text and then the presentation should match so that visual users get the same reaction as non-visual users.

I am torn on this issue, because I think it is a really bad idea (harmful in the second and third order consequences), but you are also not the first to request such a feature.

**Comment by rickysullivan** [comment]
Nesting inline elements aside.

I think I have to disagree with you on this one. I feel inline elements should by default remain inline with the option to change this preference.

**Comment by rickysullivan** [comment]
I see there's an option to add a data attribute ```data-prettydiff-ignore``` but this just adds markup to an already bloated document (html email, fun right?)

**Comment by rickysullivan** [comment]
Another example of why an inline option is needed.
The forcing of  ```<sup>``` to a newline inserts a blank space before the ```&reg;```
```
<p>
    Thanks for joining ProductName<sup>&reg;</sup> 2016.
</p>
```
Thanks for joining ProductName® 2016.

```
<p>
    Thanks for joining ProductName
    <sup>&reg;</sup>
    2016.
</p>
```
Thanks for joining ProductName ® 2016.

**Comment by prettydiff** [comment]
That is a defect and I am working it now.

**Comment by prettydiff** [comment]
Defect fixed in recently published v1.16.15.

**Comment by rickysullivan** [comment]
Thanks, but I still don't the need to force the content post ```</sup>``` to a newline.

**Comment by adbutterfield** [comment]
Hello! 
This is indeed still and issue/would be an awesome improvement. 

Back when I was still using Sublime, I was using [Sublime-HTMLPrettify](https://github.com/victorporof/Sublime-HTMLPrettify). That package has an "unformatted" option which takes an array of tags that the formatter should ignore (I think using js-beautify). The only issue is that I'm using Nunjucks templates, and Sublime-HTMLPrettify didn't format the Nunjucks tags correctly (but atom-beautify and prettydiff does!).

When switching to Atom and atom-beautify, I was pretty excited to have my Nunjucks tags formatted, but also a little bummed on losing the "unformatted" option. The prettydif "unformatted" option (http://prettydiff.com/documentation.xhtml#unformatted) doesn't do the same thing as with js-beautify, and I'm not sure that it's even working at all in atom-beautify. When I set "unformatted" to true in my config.cson, it doesn't appear to do anything differently.
